ecommerce/urls.py
from django.conf.urls import url, include

from ecommerce import views

app_name = 'ecommerce'
urlpatterns = [
    # main page
    url(r'^$', views.index, name='index'),
	# main page
    url(r'^shop/$', views.shop, name='shop'),
    # signup page
    url(r'^signup/$', views.signup, name='signup'),
    # register new user
	url(r'^register/$', views.register, name='register'),
    # login page
    url(r'^login/$', views.login, name='login'),
    # basket page
    url(r'^basket/$', views.basket, name='basket'),
	# logout page
    url(r'^logout/$', views.logout, name='logout'),
	# addbasket page
    url(r'^addbasket/$', views.addbasket, name='addbasket'),
	# removefrombasket page
    url(r'^removefrombasket/$', views.removefrombasket, name='removefrombasket'),
	# orders page
    url(r'^orders/$', views.orders, name='orders'),
	# orderproducts page
    url(r'^orderproducts/$', views.orderproducts, name='orderproducts'),
	# addpaymentmethodform page
    url(r'^addpaymentmethodform/$', views.addpaymentmethodform, name='addpaymentmethodform'),
	# addpaymentmethod page
    url(r'^addpaymentmethod/$', views.addpaymentmethod, name='addpaymentmethod'),
	# choosepayment page
    url(r'^choosepayment/$', views.choosepayment, name='choosepayment'),
	# placeorder page
    url(r'^placeorder/$', views.placeorder, name='placeorder')

]

mywebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^ecommerce/', include('ecommerce.urls')),
    url(r'^admin/', admin.site.urls),
]

ecommerce/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

	
class Product(models.Model):
    ProductID = models.AutoField(db_column='ProductId', primary_key=True)  # Field name made lowercase.
    Name = models.CharField(db_column='Name', max_length=255, blank=True, null=True)  # Field name made lowercase.
    Price = models.DecimalField(db_column='total', max_digits=7, decimal_places=2, null=True)  # Field name made lowercase. This field type is a guess.
    Description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
    Image = models.TextField(db_column='Image', blank=True, null=True)  # Field name made lowercase.
	
class User(models.Model):
    #userid = models.IntegerField(db_column='UserId', primary_key=True)  # Field name made lowercase.
    username = models.CharField(db_column='Username', max_length=255, primary_key=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=255)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=255)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=255)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=255)  # Field name made lowercase.
    phonenumber = models.CharField(db_column='PhoneNumber', max_length=255)  # Field name made lowercase.

class Address(models.Model):
    addressid = models.AutoField(db_column='AddressId', primary_key=True)  # Field name made lowercase.
    addressline1 = models.CharField(db_column='AddressLine1', max_length=255)  # Field name made lowercase.
    addressline2 = models.CharField(db_column='AddressLine2', max_length=255)  # Field name made lowercase.
    postcode = models.CharField(db_column='PostCode', max_length=255)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=255)  # Field name made lowercase.
    country = models.CharField(db_column='Country', max_length=255)  # Field name made lowercase.
    userid = models.ForeignKey(User, db_column='UserId')  # Field name made lowercase.

class Paymentmethod(models.Model):
    paymentmethodid = models.AutoField(db_column='PaymentMethodId', primary_key=True)  # Field name made lowercase.
    cardnumber = models.CharField(db_column='CardNumber', max_length=255)  # Field name made lowercase.
    expdate = models.DateField(db_column='ExpDate')  # Field name made lowercase.
    cvc = models.CharField(db_column='CVC', max_length=255)  # Field name made lowercase.
    cardholdername = models.CharField(db_column='CardHolderName', max_length=255)  # Field name made lowercase.
    billingaddressid = models.ForeignKey(Address, db_column='BillingAddressId')  # Field name made lowercase.
    userid = models.ForeignKey(User, db_column='UserId')  # Field name made lowercase.

class Order(models.Model):
    orderid = models.AutoField(db_column='OrderId', primary_key=True)  # Field name made lowercase.
    confirmed = models.NullBooleanField(db_column='Confirmed')  # Field name made lowercase.
    date = models.DateField(db_column='date', null=True)  # Field name made lowercase.
    total = models.DecimalField(db_column='total', max_digits=7, decimal_places=2, null=True)  # Field name made lowercase.
    userid = models.ForeignKey(User, db_column='UserId')  # Field name made lowercase.
    paymentmethodid = models.ForeignKey(Paymentmethod, db_column='PaymentMethodId', blank=True, null=True)  # Field name made lowercase.
    productid = models.ManyToManyField(Product, db_column='ProductId')

ecommerce/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django import template
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, RequestContext
from django.db.models import Sum
from decimal import *
from .models import Product, User, Address, Order, Paymentmethod
import math, datetime

# Create your views here.

appname = 'Ecommerce Website'

def loggedin(f):
    def test(request):
        if 'username' in request.session:
            return f(request)
        else:
            return render(request, 'ecommerce/not-logged-in.html', {})
    return test

def index(request):
    counter = 0
    # get all stored Record objects
    oldProducts = Product.objects.all()

    # make dictionary of old queries
    context = {
        'appname': appname,
        'oldProducts' : oldProducts,
		'counter' : counter
    }
    return render(request, 'ecommerce/index.html', context)

	
def shop(request):
    # get all stored Record objects
    oldProducts = Product.objects.all()
    u = request.session['username']
    context = {
        'appname': appname,
		'loggedin': True,
		'username' : u,
        'oldProducts' : oldProducts
    }
    return render(request, 'ecommerce/index.html', context)

@loggedin
def orders(request):# get all fulfilled orders
	u = request.session['username']
	user = User.objects.get(username = u)
	allOrders =  Order.objects.filter(userid = user).filter(confirmed = 1)
	address = Address.objects.filter(userid = user).first()
	context = {
        	'appname': appname,
		'loggedin': True,
		'username' : u,
        	'allOrders' : allOrders,
		'address' : address
	}
	return render(request, 'ecommerce/orders.html', context)

@loggedin
def orderproducts(request):# get all fulfilled orders
	u = request.session['username']
	orderid = request.POST['orderid']
	products =  Order.objects.get(orderid = orderid).productid.all()
	order = Order.objects.get(orderid = orderid)

	context = {
        	'appname': appname,
		'loggedin': True,
		'username' : u,
        	'products' : products,
		'order' : order
	}
	return render(request, 'ecommerce/orderproducts.html', context)

def signup(request):
    context = { 'appname': appname }
    return render(request, 'ecommerce/signup.html', context)
	
def register(request):
	u = request.POST['username']
	e = request.POST['email']
	p = request.POST['password']
	ph = request.POST['phone']
	a1 = request.POST['address1']
	a2 = request.POST['address2']
	pc = request.POST['postcode']
	fn = request.POST['firstname']
	ln = request.POST['lastname']
	ci = request.POST['city']
	co = request.POST['country']

	user = User(username=u, email=e, password=p, phonenumber=ph, firstname=fn, lastname=ln)	
	address = Address(addressline1 = a1, addressline2 = a2, postcode = pc, city = ci, country = co, userid = user)
	user.save()
	address.save()

	context = {
		'appname': appname,
        	'username' : u
	}
	return render(request, 'ecommerce/user-registered.html', context)

def login(request):
	if 'username' not in request.POST:
		context = { 'appname': appname }
		return render(request, 'ecommerce/login.html', context)
	else:
		u = request.POST['username']
		p = request.POST['password']
		try:
			member = User.objects.get(pk=u)
		except:
			return render(request, 'ecommerce/loginfailed.html')
		if p == member.password:
			request.session['username'] = u;
			request.session['password'] = p;
			return render(request, 'ecommerce/login.html', {
				'appname': appname,
				'username': u,
				'loggedin': True}
				)
		else:
			return render(request, 'ecommerce/loginfailed.html') 
	
@loggedin
def logout(request):
    if 'username' in request.session:
        u = request.session['username']
        request.session.flush()        
        context = {
            'appname': appname,
            'username': u
        }
        return render(request, 'ecommerce/logout.html', context)
    else:
        raise Http404("Can't logout, you are not logged in")

@loggedin
def basket(request):
	u = request.session['username']
	user = User.objects.get(username = u)
	order = Order.objects.filter(userid = user).filter(confirmed = 0)
	if order.exists():
		o = order.get()
		allProductsInBasket = o.productid.all()
		total = allProductsInBasket.aggregate(Sum('Price'))
		o.total = total['Price__sum']
		o.save()
		return render(request, 'ecommerce/basket.html', {
			'appname': appname,
			'loggedin': True,
			'allProductsInBasket' : allProductsInBasket,
			'username' : u,
			'total': total}
		)
	else:
		return render(request, 'ecommerce/basket.html', {
			'appname': appname,
			'loggedin': True,
			'username' : u,
			'total': 0}
		)
@loggedin
def addbasket(request):
	u = request.session['username']
	productid = request.POST['stuffNum']

	user = User.objects.get(username = u)
	order = Order.objects.filter(userid = user).filter(confirmed = 0)
	product = Product.objects.get(ProductID = productid)

	if order.exists():
		o = order.get()
	else:
		o = Order(confirmed = 0, userid = user)
		o.save()
	o.productid.add(product)


	return render(request, 'ecommerce/added.html', {
		'appname': appname,
		'loggedin': True,
		'username' : u}
	)

def removefrombasket(request):
	u = request.session['username']
	productid = request.POST['itemID']
	user = User.objects.get(username = u)
	order = Order.objects.filter(userid = user).filter(confirmed = 0)
	o = order.get()
	product = Product.objects.get(ProductID = productid)
	o.productid.remove(product)

	if order.exists():
		o = order.get()
		allProductsInBasket = o.productid.all()
		total = allProductsInBasket.aggregate(Sum('Price'))
		o.total = total['Price__sum']
		o.save()
		return render(request, 'ecommerce/basket.html', {
			'appname': appname,
			'loggedin': True,
			'allProductsInBasket' : allProductsInBasket,
			'username' : u,
			'total': total}
		)
	else:
		return render(request, 'ecommerce/basket.html', {
			'appname': appname,
			'loggedin': True,
			'username' : u,
			'total': 0}
		)

@loggedin
def addpaymentmethodform(request):
    u = request.session['username']
    context = { 'appname': appname, 'loggedin': True, 'username': u	}
    return render(request, 'ecommerce/addpaymentmethod.html', context)

@loggedin
def addpaymentmethod(request):
	u = request.session['username']

	cn = request.POST['cardnumber']
	ed = request.POST['expdate']
	chn = request.POST['cardholdername']
	cvc = request.POST['cvc']
	a1 = request.POST['address1']
	a2 = request.POST['address2']
	pc = request.POST['postcode']
	ci = request.POST['city']
	co = request.POST['country']

	user = User.objects.get(username = u)

	address = Address(addressline1 = a1, addressline2 = a2, postcode = pc, city = ci, country = co, userid = user)
	address.save()
	paymentmethod = Paymentmethod(cardnumber = cn, expdate = ed + "-01", cardholdername = chn, billingaddressid = address, cvc = cvc, userid = user )
	paymentmethod.save()

	methods = Paymentmethod.objects.filter(userid = user)	

	return render(request, 'ecommerce/choosepayment.html', {
		'appname': appname,
		'loggedin': True,
		'paymentmethods': methods,
		'username' : u}
	)

@loggedin
def choosepayment(request):
	u = request.session['username']
	user = User.objects.get(username = u)
	methods = Paymentmethod.objects.filter(userid = user)


	return render(request, 'ecommerce/choosepayment.html', {
		'appname': appname,
		'loggedin': True,
		'paymentmethods': methods,
		'username' : u}
	)

@loggedin
def placeorder(request):
	u = request.session['username']
	pid = request.POST['paymentid']
	user = User.objects.get(username = u)
	payment = Paymentmethod.objects.get(paymentmethodid = pid)
	address = Address.objects.filter(userid = user).first()
	order = Order.objects.filter(userid = user).filter(confirmed = 0)
	o = order.get()
	o.confirmed = 1
	o.paymentmethodid = payment
	o.date = datetime.datetime.now()
	o.save()
	allProductsInBasket = o.productid.all()
	return render(request, 'ecommerce/summary.html', {
		'appname': appname,
		'loggedin': True,
		'username' : u,
		'order' : o,
		'paymentmethod': payment,
		'address': address,
		'products': allProductsInBasket}
	)

ecommerce/templates/ecommerce/added.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>You have added an item to your basket successfull</center>
	<center><a href="{% url 'ecommerce:shop' %}">Please click here to continue</a></center>
{% endblock %}

ecommerce/templates/ecommerce/addpaymentmethod.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}
{% block content %}
<!-- Custom styles for this template -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/1.2.3/jquery.payment.min.js"></script>
<!-- If you're using Stripe for payments -->
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
{% if loggedin %}
<div class="container">
    <div class="all-elements">
        <!-- You can make it whatever width you want. I'm making it full width
             on <= small devices and 4/12 page width on >= medium devices -->
        
        
            <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td" >&nbsp;Payment Details</h3>
                        <div class="display-td" >                            
                            <img src="http://i76.imgup.net/accepted_c22e0.png">
                        </div>
                    </div>                    
                </div>
                <div class="panel-body">
                    <form role="form" id="payment-form" method="POST" action="{% url 'ecommerce:addpaymentmethod' %}">
					{% csrf_token %}
                        <div class="row">
                            <div class="col-xs-12">
								<div class="form-group">
                                    <label for="couponCode">CARDHOLDER'S NAME</label>
                                    <input type="text" class="form-control" name="cardholdername" />
                                </div>
                                <div class="form-group">
                                    <label for="cardNumber">CARD NUMBER</label>
                                    <div class="input-group">
                                        <input 
                                            type="tel"
                                            class="form-control"
                                            name="cardnumber"
                                            placeholder="Valid Card Number"
                                            autocomplete="cc-number"
                                            required autofocus 
                                        />
                                        <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                    </div>
                                </div>                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-7 col-md-7">
                                <div class="form-group">
                                    <label for="cardExpiry"><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span> DATE</label>
                                    <input 
                                        type="month" 
                                        class="form-control" 
                                        name="expdate"
                                        placeholder="MM / YY"
                                        autocomplete="cc-exp"
                                        required 
                                    />
                                </div>
                            </div>
                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group">
                                    <label for="cardCVC">CV CODE</label>
                                    <input 
                                        type="tel" 
                                        class="form-control"
                                        name="cvc"
                                        placeholder="CVC"
                                        autocomplete="cc-csc"
                                        required
                                    />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="address1">ADDRESS LINE 1</label>
                                    <input type="text" class="form-control" name="address1" />
                                </div>
								<div class="form-group">
                                    <label for="address2">ADDRESS LINE 2</label>
                                    <input type="text" class="form-control" name="address2" />
                                </div>
								<div class="form-group">
                                    <label for="city">CITY</label>
                                    <input type="text" class="form-control" name="city" />
                                </div>
								<div class="form-group">
                                    <label for="country">COUNTRY</label>
                                    <input type="text" class="form-control" name="country" />
                                </div>
								<div class="form-group">
                                    <label for="postCode">POST CODE</label>
                                    <input type="text" class="form-control" name="postcode" />
                                </div>
                            </div>                        
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="subscribe btn btn-success btn-lg btn-block" type="submit">Add Payment Method</button>
                            </div>
                        </div>
                        <div class="row" style="display:none;">
                            <div class="col-xs-12">
                                <p class="payment-errors"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>            
            <!-- CREDIT CARD FORM ENDS HERE -->
                  
        
    </div>
</div>
{% else %}
Not Logged in
{% endif %}
{% endblock %}

ecommerce/templates/ecommerce/basket.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}
{% block content %}
<!-- Custom styles for this template -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
{% if loggedin %}
<div class="container">
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%">Product</th>
							<th style="width:10%">Price</th>
							<th style="width:10%"></th>
						</tr>
					</thead>
					<tbody>
					{% for Basket in allProductsInBasket %}
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs"><img src="/static/ecommerce/img/{{ Basket.Image }}" alt="Item image" class="img-responsive"/></div>
									<div class="col-sm-10">
										<h4 class="nomargin">{{ Basket.Name }}</h4>
										<p>{{ Basket.Description }}</p>
									</div>
								</div>
							</td>
							<td data-th="Price">${{ Basket.Price }}</td>
							<td class="actions" data-th="">
							
							  <form method='POST' action="{% url 'ecommerce:removefrombasket' %}">
							  {% csrf_token %}
							  <input type="hidden" name="itemID" value="{{ Basket.ProductID }}">
							  <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash-o"></i></button>
							  </form>							
							</td>
						</tr>
					{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<td><a href="{% url 'ecommerce:shop' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td class="hidden-xs text-center"><strong>Total £{% if total.Price__sum %}{{total.Price__sum}}{% else %}0{% endif %}</strong></td>
							<td><a href="{% url 'ecommerce:choosepayment' %}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>
</div>		
{% endif %}
{% endblock %}

ecommerce/templates/ecommerce/checkout.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<meta http-equiv="refresh" content="0; URL={% url 'ecommerce:{{viewname}}' %}">
{% endblock %}

ecommerce/templates/ecommerce/choosepayment.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}
{% block content %}
<!-- Custom styles for this template -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<link href="{% static "ecommerce/orderstyle.css" %}" rel="stylesheet">
{% if loggedin %}
<div class="container">
			<div class="col-xs-12">
				<div class="text-right">
					<a href="{% url 'ecommerce:addpaymentmethodform' %}" class="btn btn-default">Add New Payment Method</a>
				</div>
			</div>
			</br>
			</br>
			</br>
        <div class="col-sm-12">
		{% for Payment in paymentmethods %}
                <div class="bs-calltoaction bs-calltoaction-default">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">Cardholder's name: {{ Payment.cardholdername }}</h1>
                            <div class="cta-desc">
                                <p>Card Number: {{Payment.cardnumber}}</p>
                            </div>
                        </div>
                        <div class="col-md-3 cta-button">
							<form method='POST' action="{% url 'ecommerce:placeorder' %}">
							{% csrf_token %}
							<input type="hidden" name="paymentid" value="{{ Payment.paymentmethodid }}">
							<button class="btn btn-lg btn-block btn-default" type="submit">Pay</button>
							</form>
                        </div>
                     </div>
                </div>
		{% endfor %}
        </div>
    </div>	
{% else %}
Not logged in
{% endif %}
{% endblock %}

ecommerce/templates/ecommerce/login.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
    <!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
<script src="{% static 'mainapp/jquery-1.11.2.js' %}"></script>
<script src="{% static 'mainapp/ajax.js' %}"></script>
<div class="all-elements">
	{% if loggedin %}
		<p class="text-center">You are now logged in.</p>
		<p class="text-center">Please <a href="{% url 'ecommerce:shop' %}">click here</a> to continue shopping.</p>
		<br><br>
	{% else %}
		<form method='POST' action="{% url 'ecommerce:login' %}">
			{% csrf_token %}
			<h2 class="form-signin-heading">Please log in</h2>
			<label for="inputEmail" class="sr-only">Username</label>
			<input type="text" id="inputEmail" class="form-control" maxlength='16' name='username' placeholder="Username" required autofocus>
			<label for="inputPassword" class="sr-only">Password</label>
			<input type="password" id="inputPassword" class="form-control" name='password' placeholder="Password" required>
			<div class="checkbox">
			<label>
				<input type="checkbox" value="remember-me"> Remember me
			</label>
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
	{% endif %}
    </div> <!-- /container -->
{% endblock %}

ecommerce/templates/ecommerce/loginfailed.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>The user does not exist or the password is incorrect!</center>
	<center><a href="{% url 'ecommerce:login' %}">Please click here to try again</a></center>
{% endblock %}

ecommerce/templates/ecommerce/logout.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>You have logged out successfully</center>
	<center><a href="{% url 'ecommerce:index' %}">Please click here to go back to the shop page</a></center>
{% endblock %}

ecommerce/templates/ecommerce/not-logged-in.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>You are currently not logged in</center>
	<center><a href="{% url 'ecommerce:login' %}">Click here to Log In</a></center>
{% endblock %}

ecommerce/templates/ecommerce/orderproducts.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}
{% block content %}
<!-- Custom styles for this template -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
{% if loggedin %}
<div class="container">
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%">Product</th>
							<th style="width:10%">Price</th>
							<th style="width:10%"></th>
						</tr>
					</thead>
					<tbody>
					{% for Basket in products %}
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs"><img src="/static/ecommerce/img/{{ Basket.Image }}" alt="Item image" class="img-responsive"/></div>
									<div class="col-sm-10">
										<h4 class="nomargin">{{ Basket.Name }}</h4>
										<p>{{ Basket.Description }}</p>
									</div>
								</div>
							</td>
							<td data-th="Price">${{ Basket.Price }}</td>
							<td class="actions" data-th="">					
							</td>
						</tr>
					{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<td><a href="{% url 'ecommerce:orders' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Back to Orders List</a></td>
							<td class="hidden-xs text-center"><strong>Total ${{ order.total }}</strong></td>
						</tr>
					</tfoot>
				</table>
</div>		
{% endif %}
{% endblock %}

ecommerce/templates/ecommerce/paymentsuccessful.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>Payment successfull! You will receive an email confirmation shortly.</center>
	<center><a href="{% url 'ecommerce:shop' %}">Please click here to continue shopping</a></center>
{% endblock %}

ecommerce/templates/ecommerce/user-registered.html
{% extends "ecommerce/base.html" %}

{% load staticfiles %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="{% static "ecommerce/signin.css" %}" rel="stylesheet">
	<center>You have registered successfull</center>
	<center><a href="{% url 'ecommerce:login' %}">Please click here to Log In</a></center>
{% endblock %}